name: Fetch QDII Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1-5' # 北京时间周一至周五 09:00

jobs:
  fetch-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install yfinance pandas pytz

      - name: Run script
        run: python get_data.py

      - name: Push results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # 仅处理固定命名的最新数据文件
          if [ -f output/qdii_daily_latest.csv ]; then
            git add output/qdii_daily_latest.csv
            git commit -m "Update QDII Latest: $(date +'%Y-%m-%d %H:%M')" || exit 0
            git pull --rebase origin main
            git push origin main
          else
            echo "qdii_daily_latest.csv not found"
          fi
